### ISSUE TITLE
how to pass methods into javascript?

### ISSUE THREAD

**Issue by fap2this1** [spatie/laravel-blade-javascript#16]
Hi

Thanks for making  laravel-blade-javascript. 

is there a way I can pass my class functions to javascript?

`@javascript('mybjects', myObjects)
`

**Comment by sebastiandedeyne** [comment]
What do you mean by methods? The result of the methods?

It's not possible to pass functionality from PHP to JS, only data.

**Comment by fap2this1** [comment]
sorry i mean:
if i have following class:

class myClass extends Model
{
    public function needTosend()
    {
         // some functionality

        return 'test'
    }
}

I want to use this function in my javascript. How can I do that?

**Comment by fap2this1** [comment]
Perhaps I can use Renderer ? how does that work?

https://github.com/spatie/laravel-blade-javascript/blob/master/src/Renderer.php

**Comment by fap2this1** [comment]
anyone?

**Comment by sebastiandedeyne** [comment]
If you're working with Eloquent models, I'd recommend setting up what can be serialized. If you want to add method results, follow the steps in the Eloquetn documentation.

https://laravel.com/docs/master/eloquent-serialization#appending-values-to-json

Since under the hood, this package will call `toJson`, the following code would work then:

```
@javascript('myModel', $myModel)
```
